# Generated by Django 3.2.6 on 2021-09-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buttonText', models.CharField(default='', max_length=5000)),
                ('buttonType', models.CharField(default='', max_length=5000)),
                ('buttonIcon', models.CharField(default='', max_length=5000)),
                ('answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ButtonRowQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberButtons', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=None)),
                ('title', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='NumberScaleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minTitle', models.CharField(default='', max_length=5000)),
                ('middleTitle', models.CharField(default='', max_length=5000)),
                ('maxTitle', models.CharField(default='', max_length=5000)),
                ('interval', models.IntegerField(default=None)),
                ('numberMax', models.IntegerField(default=None)),
                ('numberMin', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPostQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleURL', models.URLField(default='', max_length=5000)),
                ('articleTitle', models.CharField(default='', max_length=5000)),
                ('articleSource', models.CharField(default='', max_length=5000)),
                ('articleImageLink', models.CharField(default='', max_length=5000)),
                ('articleStyle', models.CharField(default='', max_length=5000)),
                ('articleSnippet', models.CharField(default='', max_length=5000)),
                ('articleNumLikes', models.IntegerField(default=0)),
                ('articleNumComments', models.IntegerField(default=0)),
                ('articleNumShares', models.IntegerField(default=0)),
                ('articleCommentsOn', models.BooleanField(default=False)),
                ('articleSharedOn', models.BooleanField(default=False)),
                ('articleLikesOn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextboxQuestionDecimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('textboxMax', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('textboxMin', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='TextboxQuestionNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.IntegerField(default=None)),
                ('textboxMax', models.IntegerField(default=None)),
                ('textboxMin', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='TextboxQuestionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(default='', max_length=5000)),
                ('textboxMax', models.IntegerField(default=None)),
                ('textboxMin', models.IntegerField(default=None)),
            ],
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='timelimit_minutes',
            new_name='timelimitMinutes',
        ),
        migrations.RemoveField(
            model_name='multichoicequestion',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='consent_text',
        ),
        migrations.AddField(
            model_name='block',
            name='title',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='multichoicequestion',
            name='isCheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multichoicequestion',
            name='isDropDown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multichoicequestion',
            name='textboxMax',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='multichoicequestion',
            name='textboxMin',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='survey',
            name='consentText',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='language',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.DeleteModel(
            name='TextboxQuestion',
        ),
        migrations.AddField(
            model_name='textboxquestiontext',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.question'),
        ),
        migrations.AddField(
            model_name='textboxquestionnumber',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.question'),
        ),
        migrations.AddField(
            model_name='textboxquestiondecimal',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.question'),
        ),
        migrations.AddField(
            model_name='socialpostquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.question'),
        ),
        migrations.AddField(
            model_name='numberscalequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.question'),
        ),
        migrations.AddField(
            model_name='buttonrowquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.question'),
        ),
        migrations.AddField(
            model_name='buttonquestion',
            name='buttonRow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.buttonrowquestion'),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='UniqueChoice'),
        ),
    ]
