# Generated by Django 3.2.7 on 2021-09-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0003_block_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberscalequestion',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='numberscalequestion',
            name='numberMax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='numberscalequestion',
            name='numberMin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='textboxquestiondecimal',
            name='query',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='textboxquestiondecimal',
            name='textboxMax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='textboxquestiondecimal',
            name='textboxMin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='textboxquestionnumber',
            name='query',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='textboxquestionnumber',
            name='textboxMax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='textboxquestionnumber',
            name='textboxMin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='textboxquestiontext',
            name='textboxMax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='textboxquestiontext',
            name='textboxMin',
            field=models.IntegerField(default=0),
        ),
    ]
