# Generated by Django 3.2.8 on 2021-10-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0007_auto_20211010_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='textboxquestiontext',
            name='validate',
            field=models.BooleanField(default=False),
        ),
    ]
