# Generated by Django 3.2.8 on 2021-10-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0008_textboxquestiontext_validate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='description',
            field=models.CharField(blank=True, default='', max_length=15000),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='buttonquestion',
            name='buttonIcon',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='buttonquestion',
            name='buttonText',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='buttonquestion',
            name='buttonType',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='multichoice',
            name='title',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='numberscalequestion',
            name='maxTitle',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='numberscalequestion',
            name='middleTitle',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='numberscalequestion',
            name='minTitle',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='socialpostquestion',
            name='articleImageLink',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='socialpostquestion',
            name='articleSnippet',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='socialpostquestion',
            name='articleSource',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='socialpostquestion',
            name='articleStyle',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='socialpostquestion',
            name='articleTitle',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='socialpostquestion',
            name='articleURL',
            field=models.URLField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='consentText',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='language',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='textboxquestiontext',
            name='query',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
