# Generated by Django 3.2.8 on 2021-10-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0009_auto_20211031_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
