# Generated by Django 3.2.8 on 2021-10-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0010_alter_question_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpostquestion',
            name='articleStyle',
            field=models.CharField(blank=True, default='Twitter', max_length=5000),
        ),
    ]
