# Generated by Django 3.2.8 on 2021-10-31 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0011_alter_socialpostquestion_articlestyle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialpostquestion',
            old_name='articleSharedOn',
            new_name='articleSharesOn',
        ),
    ]
