# Generated by Django 3.2.8 on 2021-10-31 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0012_rename_articlesharedon_socialpostquestion_articleshareson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialpostquestion',
            old_name='articleNumComments',
            new_name='articleComments',
        ),
        migrations.RenameField(
            model_name='socialpostquestion',
            old_name='articleNumLikes',
            new_name='articleLikes',
        ),
        migrations.RenameField(
            model_name='socialpostquestion',
            old_name='articleNumShares',
            new_name='articleShares',
        ),
    ]
