# Generated by Django 3.2.8 on 2021-11-01 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0010_auto_20211030_0954'),
        ('surveybuilder', '0013_auto_20211031_0338'),
    ]

    operations = [
    ]
