# Generated by Django 3.2.8 on 2021-11-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0014_merge_0010_auto_20211030_0954_0013_auto_20211031_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draganddropcard',
            name='title',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='draganddropchoice',
            name='title',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
