# Generated by Django 3.2.7 on 2021-10-08 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkGeneration',
            fields=[
                ('link', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('survey_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('survey_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_info', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.JSONField(null=True)),
                ('identifier', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
