# Generated by Django 3.2.7 on 2021-10-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveytaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='contact_info',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
